version: '3'

services:
  frontend:
    build:
      context: ./Frontend/factored-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./Backend/app/database:/app/app/database